# Generated by Django 3.0.5 on 2020-07-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribute',
            name='is_moderator',
        ),
    ]
