# Generated by Django 3.0.5 on 2020-05-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='f',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='l',
        ),
    ]
