# Generated by Django 3.0.5 on 2020-07-30 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rex_app', '0002_remove_userattribute_is_moderator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendadditionaldetail',
            unique_together={('user_attribute', 'user')},
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
