# Generated by Django 3.0.5 on 2020-05-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0002_auto_20200508_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='f',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='l',
            new_name='last',
        ),
    ]
