# Generated by Django 3.0.5 on 2020-07-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0003_auto_20200730_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
