# Generated by Django 3.0.5 on 2020-06-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0004_auto_20200624_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='answered_by',
            new_name='commented_by',
        ),
    ]
