# Generated by Django 3.0.5 on 2020-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0004_userattribute_reputation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('moderator', 'Can moderate'), ('voter', 'Can upvote/downvote'), ('', ''))},
        ),
        migrations.AlterField(
            model_name='friendadditionaldetail',
            name='status',
            field=models.IntegerField(choices=[(1, 'AWAITING_APPROVAL'), (2, 'REJECTED'), (3, 'APPROVED')]),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='background_color',
            field=models.IntegerField(choices=[('#212529', 'Dark'), ('#001442', 'Blue'), ('#00321b', 'Green')]),
        ),
    ]
