# Generated by Django 3.0.5 on 2020-06-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0003_auto_20200619_1533'),
        ('rex_app', '0005_auto_20200624_1339'),
    ]

    operations = [
    ]
