# Generated by Django 3.0.5 on 2020-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0006_auto_20200807_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=99999),
            preserve_default=False,
        ),
    ]
