# Generated by Django 3.0.5 on 2020-07-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0006_merge_20200624_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattribute',
            name='background_color',
            field=models.IntegerField(choices=[(1, 'green'), (2, 'blue')]),
        ),
    ]
