# Generated by Django 3.0.5 on 2020-07-03 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rex_app', '0007_auto_20200703_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=99999)),
                ('from_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_user_reverse', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='to_user_reverse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
