# Generated by Django 3.0.5 on 2020-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0008_auto_20200807_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('moderator', 'Can moderate'), ('voter', 'Can upvote/downvote'))},
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='avatar',
            field=models.CharField(choices=[('1', 'fab fa-500px'), ('2', 'far fa-angry'), ('3', 'fas fa-backspace'), ('4', 'fas fa-atom'), ('5', 'fab fa-battle-net'), ('6', 'fas fa-biohazard'), ('7', 'fas fa-braille'), ('8', 'fas fa-burn'), ('9', 'fab fa-canadian-maple-leaf'), ('10', 'fas fa-car-crash')], default='1', max_length=99999),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='background_color',
            field=models.IntegerField(choices=[(1, '#212529'), (2, '#001442'), (3, '#00321b')], default=1),
        ),
    ]
