# Generated by Django 3.0.5 on 2020-07-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0009_auto_20200703_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='avatar',
            field=models.CharField(choices=[('1', 'fab fa-500px'), ('2', 'far fa-angry')], default='fab fa-500px', max_length=99999),
            preserve_default=False,
        ),
    ]
