# Generated by Django 3.0.5 on 2020-07-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0011_auto_20200716_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattribute',
            name='timezone',
            field=models.CharField(choices=[('1', 'Asia/Taipei'), ('2', 'Etc/GMT'), ('3', 'Etc/GMT+0'), ('4', 'Etc/GMT+1'), ('5', 'Etc/GMT+10'), ('6', 'Etc/GMT+11'), ('7', 'Etc/GMT+12'), ('8', 'Etc/GMT+2'), ('9', 'Etc/GMT+3'), ('10', 'Etc/GMT+4'), ('11', 'Etc/GMT+5'), ('12', 'Etc/GMT+6'), ('13', 'Etc/GMT+7'), ('14', 'Etc/GMT+8'), ('15', 'Etc/GMT+9'), ('16', 'Etc/GMT-0'), ('17', 'Etc/GMT-1'), ('18', 'Etc/GMT-10'), ('19', 'Etc/GMT-11'), ('20', 'Etc/GMT-12'), ('21', 'Etc/GMT-13'), ('22', 'Etc/GMT-14'), ('23', 'Etc/GMT-2'), ('24', 'Etc/GMT-3'), ('25', 'Etc/GMT-4'), ('26', 'Etc/GMT-5'), ('27', 'Etc/GMT-6'), ('28', 'Etc/GMT-7'), ('29', 'Etc/GMT-8'), ('30', 'Etc/GMT-9')], max_length=99999),
        ),
    ]
