# Generated by Django 3.0.5 on 2020-07-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0012_auto_20200716_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
