# Generated by Django 3.0.5 on 2020-07-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0014_auto_20200717_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattribute',
            name='timezone',
        ),
    ]
