# Generated by Django 3.0.5 on 2020-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0015_remove_userattribute_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattribute',
            name='is_moderator',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
