# Generated by Django 3.0.5 on 2020-07-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0017_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rex_app.UserAttribute')),
            ],
            bases=('rex_app.userattribute',),
        ),
    ]
