# Generated by Django 3.0.5 on 2020-07-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rex_app', '0018_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
